-- LOREAL1.FCST_DATA_1 definition

CREATE TABLE "FCST_DATA_1" 
   (	"CUSTOMER_ID" VARCHAR2(300), 
	"CUSTOMER_NAME" VARCHAR2(300), 
	"ADDRESS1" VARCHAR2(300), 
	"CHANNEL" VARCHAR2(300), 
	"CUSTOMER_NUMBER" VARCHAR2(300), 
	"CITY" VARCHAR2(300), 
	"COUNTRY" VARCHAR2(300), 
	"CONTACT_PERSON" VARCHAR2(300), 
	"ORG_ID" VARCHAR2(300), 
	"REGION" VARCHAR2(300), 
	"ORDER_TYPE" VARCHAR2(300), 
	"PRINCIPAL_CHANNEL_CODE" VARCHAR2(300), 
	"DATA_TYPE" VARCHAR2(300), 
	"DISTRIBUTORCODE" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;


-- LOREAL1.FSLS_LOREAL_1 definition

CREATE TABLE "FSLS_LOREAL_1" 
   (	"DISTRIBUTOR_CODE" VARCHAR2(300), 
	"TRANSACTION_TYPE" VARCHAR2(300), 
	"FINAL_CUSTOMER_NUMBER" VARCHAR2(300), 
	"SKU_DESCRIPTION" VARCHAR2(300), 
	"DISTRIBUTOR_PROD_CODE" VARCHAR2(300), 
	"BARCODE" VARCHAR2(300), 
	"DATE_" VARCHAR2(300), 
	"DESTINATION_WAREHOUSE" VARCHAR2(300), 
	"QTY" VARCHAR2(300), 
	"DISTRIBUTOR_CAT" VARCHAR2(300), 
	"NET_SALE" VARCHAR2(300), 
	"CURRENCY_CODE" VARCHAR2(300), 
	"VENDOR_CODE" VARCHAR2(300), 
	"DISCOUNT_VALUE" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;


-- LOREAL1.FSTK_DATA_FILE_1 definition

CREATE TABLE "FSTK_DATA_FILE_1" 
   (	"DISTRIBUTOR_CODE" VARCHAR2(300), 
	"SKU_DESC" VARCHAR2(300), 
	"DISTRIBUTORPRODUCTCODE" VARCHAR2(300), 
	"BARCODE" VARCHAR2(300), 
	"PERIOD" VARCHAR2(300), 
	"SALEABLE_STOCK" VARCHAR2(300), 
	"DAMAGED_STOCK" VARCHAR2(300), 
	"EXPIRED_STOCK" VARCHAR2(300), 
	"STOCK_IN_TRANSFER" VARCHAR2(300), 
	"TP" VARCHAR2(300), 
	"CURRENCY" VARCHAR2(300), 
	"SHIPTO" VARCHAR2(300), 
	"VENDOR_CODE" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;


-- LOREAL1.LOREAL_SALES definition

CREATE TABLE "LOREAL_SALES" 
   (	"DISTRIBUTOR_CODE" VARCHAR2(300), 
	"TRANSACTION_TYPE" VARCHAR2(300), 
	"FINAL_CUSTOMER_NUMBER" VARCHAR2(300), 
	"SKU_DESCRIPTION" VARCHAR2(300), 
	"DISTRIBUTOR_PROD_CODE" VARCHAR2(300), 
	"BARCODE" VARCHAR2(300), 
	"DATE_" NUMBER, 
	"DESTINATION_WAREHOUSE" VARCHAR2(300), 
	"QTY" VARCHAR2(300), 
	"DISTRIBUTOR_CAT" VARCHAR2(300), 
	"NET_SALE" VARCHAR2(300), 
	"CURRENCY_CODE" VARCHAR2(300), 
	"VENDOR_CODE" VARCHAR2(300), 
	"DISCOUNT_VALUE" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;

CREATE INDEX "LOREAL_SALES_DATE__IDX" ON "LOREAL_SALES" ("DATE_") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;


-- LOREAL1.LOREAL_SALES_DATA definition

CREATE TABLE "LOREAL_SALES_DATA" 
   (	"ORG_ID" VARCHAR2(300), 
	"ORG_DESC" VARCHAR2(300), 
	"TRX_DATE" DATE, 
	"TRX_NUMBER" VARCHAR2(300), 
	"BOOKER_ID" VARCHAR2(300), 
	"BOOKER_NAME" VARCHAR2(300), 
	"SUPPLIER_ID" VARCHAR2(300), 
	"SUPPLIER_NAME" VARCHAR2(300), 
	"BUSINESS_LINE_ID" VARCHAR2(300), 
	"BUSINESS_LINE" VARCHAR2(300), 
	"CHANNEL" VARCHAR2(300), 
	"CUSTOMER_ID" VARCHAR2(300), 
	"CUSTOMER_NUMBER" VARCHAR2(300), 
	"CUSTOMER_NAME" VARCHAR2(300), 
	"SALES_ORDER_TYPE" VARCHAR2(300), 
	"INVENTORY_ITEM_ID" VARCHAR2(300), 
	"ITEM_CODE" VARCHAR2(300), 
	"DESCRIPTION" VARCHAR2(300), 
	"UNIT_SELLING_PRICE" VARCHAR2(300), 
	"SOLD_QTY" VARCHAR2(300), 
	"BONUS_QTY" VARCHAR2(300), 
	"CLAIMABLE_DISCOUNT" VARCHAR2(300), 
	"UN_CLAIMABLE_DISCOUNT" VARCHAR2(300), 
	"TAX_RECOVERABLE" VARCHAR2(300), 
	"GROSS" VARCHAR2(300), 
	"REASON_CODE" VARCHAR2(300), 
	"SUPPLIER_CODE" VARCHAR2(300), 
	"ORDER_DATE" VARCHAR2(300), 
	"LEGACY_ORDER_NUMBER" VARCHAR2(300), 
	"TSO_CODE" VARCHAR2(300)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOREAL1" ;


-- LOREAL1.NEWTABLE definition

CREATE TABLE "NEWTABLE" 
   (	"COLUMN1" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "LOREAL1" ;


-- LOREAL1.VW_FCST_LOREAL_1 source

CREATE OR REPLACE FORCE VIEW "VW_FCST_LOREAL_1" ("DISTRIBUTORCODE", "ClientCode", "Description", "Address1", "Address2", "CITY", "County", "COUNTRY", "ContactPerson", "ContactEmail", "ContactPhone", "Fax", "LicTradNum", "CurrentyInvoice", "ZipCode", "CHANNEL", "accountype1", "accountype2", "accountype3", "accountype4", "activestatus", "turnover", "currency", "REGION") AS 
  SELECT
	'CE014' DISTRIBUTORCODE ,
	CUSTOMER_ID "ClientCode",
	CUSTOMER_NAME "Description",
	ADDRESS1 "Address1",
	NULL "Address2",
	CITY ,
	NULL "County",
	COUNTRY ,
	CONTACT_PERSON "ContactPerson",
	NULL "ContactEmail",
	NULL "ContactPhone",
	NULL "Fax",
	NULL "LicTradNum" ,
	'PKR' "CurrentyInvoice",
	NULL "ZipCode",
	PRINCIPAL_CHANNEL_CODE  CHANNEL ,
	'CPD' "accountype1",
	NULL "accountype2",
	NULL "accountype3",
	NULL "accountype4",
	'Y' "activestatus",
	'0' "turnover",
	'PKR' "currency",
	Region region
FROM
	FCST_DATA_1
	WHERE 1=1 AND CUSTOMER_ID  IN (SELECT 
DISTINCT FINAL_CUSTOMER_NUMBER 
FROM FSLS_LOREAL_1 fl WHERE 1=1 AND SUBSTR(TO_NUMBER(DATE_),-2)>1 )
	;


-- LOREAL1.VW_FSTK_LOREAL_1 source

CREATE OR REPLACE FORCE VIEW "VW_FSTK_LOREAL_1" ("DISTRIBUTOR_CODE", "Sku_Description", "DISTRIBUTORPRODUCTCODE", "EAN/BarCode", "PERIOD", "Normal_Stock", "Damage_Stock", "Quality", "Expired", "STOCK_IN_TRANSFER", "VENDOR_CODE", "Landed_Cost_price(MAP)", "CURRENCY", "SHIPTO") AS 
  SELECT 
DISTRIBUTOR_CODE,
SKU_DESC "Sku_Description",
DISTRIBUTORPRODUCTCODE,
BARCODE "EAN/BarCode",
PERIOD,
SALEABLE_STOCK "Normal_Stock",
DAMAGED_STOCK "Damage_Stock",
NULL "Quality",
EXPIRED_STOCK "Expired",
STOCK_IN_TRANSFER,
VENDOR_CODE,
TP "Landed_Cost_price(MAP)",
CURRENCY,
SHIPTO
FROM FSTK_DATA_FILE_1 fdf ;