

SELECT DISTINCT COMPANY_CODE 
FROM PHNX_SALES_DETAIL_DATA psdd ;

SELECT count(*) FROM  GROUP_SALES_DETAIL_DATA;
SELECT * FROM  GROUP_SALES_DETAIL_DATA;

SELECT  count(*) FROM PHNX_SALES_DATA_LOG psdl ;
SELECT * FROM PHNX_SALES_DATA_LOG psdl WHERE TRX_DATE BETWEEN '20230701' AND '20230731';

SELECT count(*) FROM  PHNX_SALES_DETAIL_DATA psdd WHERE BILLING_DATE  BETWEEN '20230701' AND '20230720';;
SELECT * FROM  PHNX_SALES_DETAIL_DATA WHERE BILLING_DATE  BETWEEN '20230701' AND '20230720';


